/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    @Test
    public void testScanner(){
        assertEquals(
                "This should give me line 2.",
                "Line 2: Missing semicolon. ",
                App.linter("/Users/danle/codefellows/java401/java-fundamentals/alice/src/main/resources/gates.js")
        );
    }
    @Test
    public void testScannerMany(){

        assertEquals(
                "This should give me line 2, 3 and 4.",
                "Line 2: Missing semicolon. Line 3: Missing semicolon. Line 4: Missing semicolon. ",
                App.linter("/Users/danle/codefellows/java401/java-fundamentals/linter/src/main/resources/errors.js")
        );
    }
    @Test
    public void testScannerEmpty(){

        assertEquals(
                "This should give me line 2, 3 and 4.",
                "",
                App.linter("/Users/danle/codefellows/java401/java-fundamentals/linter/src/main/resources/empty.js")
        );
    }
    @Test
    public void testScannerNoErrors(){

        assertEquals(
                "This should give me line 2, 3 and 4.",
                "",
                App.linter("/Users/danle/codefellows/java401/java-fundamentals/linter/src/main/resources/noerrors.js")
        );
    }
}
