/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        linter("/Users/danle/codefellows/java401/java-fundamentals/alice/src/main/resources/gates.js");
    }
    public static String linter(String path){
        int line = 0;
        System.out.println(path);
        String message = "";
        try{
            Scanner reader = new Scanner(new File(path));
            while(reader.hasNext()){
                String currentLine = reader.nextLine();
                line++;
                if(!currentLine.contains("{") && !currentLine.contains("}") &&
                        !currentLine.contains("if") && !currentLine.contains("else") ){
                    if(!currentLine.contains(";")){
                        message += ("Line " + line + ": Missing semicolon. ");
                    }
                }
        }
            System.out.println("this is message" + message);
            return message;
        }
        catch(FileNotFoundException e) {
            System.out.println("Huge problem no file");
        }
        return message;
    }
}
