/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    @Test
    public void testLengthOfArray(){
        int[] answer = new int[5];
        int size = answer.length;
        assertEquals(
              "This should return the length of the array.",
                size,
                Library.roll(5).length
        );
    }
    @Test
    public void testcontainsDuplicatesFalse(){
        assertEquals(
                "this should come back false.",
                false,
                Library.containsDuplicates(new int[]{1,2,3,4,5})
        );
    }
    @Test
    public void testcontainsDuplicatesTrue(){
        assertEquals(
                "this should come back false.",
                true,
                Library.containsDuplicates(new int[]{1,2,3,4,5,1})
        );
    }
    @Test
    public void testAverage(){
        assertEquals(
          "this should give back an average.",
          15,
          Library.average(new int[]{5,10,15,20,25})
        );
    }
    @Test
    public void testLowAverages(){
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        int answer = 57;
        assertEquals(
                "this should return 57 which is the lowest.",
                answer,
                Library.lowAverages(weeklyMonthTemperatures)
        );
    }
}
