/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;
import java.util.Random;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }


    public static int[] roll(int num){
        int[] rollArray = new int[num];
        for(int i = 0; i < num; i++) {
            rollArray[i] = (int) (1 + Math.random() * (6 - 1));
        }
        return rollArray;
    }

    public static boolean containsDuplicates(int[] arr){
        for(int i = 0; i<arr.length;i++){
            for(int j = i + 1; j< arr.length;j++){
                if(arr[i] == arr[j]){
                    return true;
                }
            }
        }
        return false;
    }

    public static int containsDuplicates(int[][] arr){
        int low = 0;
        for(int i = 0; i<arr.length;i++){
            int currentSum = 0;
            for(int j = 0; j<arr[i].length;j++){
                currentSum += arr[i][j];
            }
            int average = currentSum/arr[i].length;
            if(low == 0){
                low = average;
            }
            else if(low > average){
                low = average;
            }
        }
        return low;
    }
}
