/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package alice;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Scanner;
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());
    }
    public static String[] characters = new String[]{"cat","alice","queen"};

    public static void findCommonAliceChars(){
        try{
            HashSet<String> charSet = new HashSet<>(Arrays.asList(characters));
            HashMap<String, Integer> characterCounts = new HashMap<>();
            for(String character : charSet){
                characterCounts.put(character, 0);
            }
            Scanner aliceReader =  new Scanner(new File("alice.txt"));
            while(aliceReader.hasNext()){
                String word = aliceReader.next().toLowerCase();
                System.out.println(aliceReader.next());

                if(charSet.contains(word)){
                    characterCounts.put(word, characterCounts.get(word) + 1);
                }
            }

            for(String character : characterCounts.keyset()){
                System.out.println(String.format("%s: %d", character, characterCounts.get(character)));
            }
        }
        catch(FileNotFoundException ex){
            System.out.println("Nothing");
        }
    }
}
